apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-wildcard-rbac
  annotations:
    policies.kyverno.io/title: Restrict Wildcard in RBAC
    policies.kyverno.io/category: RBAC Security
    policies.kyverno.io/severity: high
    cis-benchmark: "4.1.3"
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: restrict-wildcard-resources
    match:
      any:
      - resources:
          kinds:
          - ClusterRole
          - Role
    exclude:
      any:
      - resources:
          names:
          - cluster-admin
          - admin
          - edit
          - view
          - system:*
      - resources:
          namespaces:
          - kube-system
          - aks-command
          - kyverno
          - security
    validate:
      message: "Wildcard in resources not allowed (CIS 4.1.3)"
      foreach:
      - list: "request.object.rules[]"
        deny:
          conditions:
            any:
            - key: "*"
              operator: AnyIn
              value: "{{ element.resources[] }}"

  - name: restrict-wildcard-verbs
    match:
      any:
      - resources:
          kinds:
          - ClusterRole
          - Role
    exclude:
      any:
      - resources:
          names:
          - cluster-admin
          - admin
          - edit
          - system:*
      - resources:
          namespaces:
          - kube-system
          - aks-command
          - kyverno
          - security
    validate:
      message: "Wildcard in verbs not allowed (CIS 4.1.3)"
      foreach:
      - list: "request.object.rules[]"
        deny:
          conditions:
            any:
            - key: "*"
              operator: AnyIn
              value: "{{ element.verbs[] }}"
